apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ble-monitoring

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - podmonitor.yaml

configMapGenerator:
  - name: ble-collector-config
    literals:
      - TARGET_MAC_ADDRESSES=D4:35:34:35:68:4D,F2:B2:02:06:7C:49
      - LEGACY_MAC_ADDRESSES=D4:35:34:35:68:4D

labels:
  - pairs:
      app.kubernetes.io/name: ble-collector
      app.kubernetes.io/part-of: ble-monitoring
    includeSelectors: true

