apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ble-collector
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ble-collector
  namespaceSelector:
    matchNames:
      - ble-monitoring
  podMetricsEndpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 5s
      scheme: http
