apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ble-collector
  labels:
    app: ble-collector
spec:
  selector:
    matchLabels:
      app: ble-collector
  template:
    metadata:
      labels:
        app: ble-collector
    spec:
      hostNetwork: true
      # hostPID not strictly required here; keep false unless needed
      containers:
      - name: ble-collector
        image: ghcr.io/yum-ae/ble-collector:latest-arm64
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http-metrics
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        volumeMounts:
        - name: dbus
          mountPath: /run/dbus
        - name: sys-bluetooth
          mountPath: /sys/class/bluetooth
          readOnly: true
        - name: dev
          mountPath: /dev
      volumes:
      - name: dbus
        hostPath:
          path: /run/dbus
      - name: sys-bluetooth
        hostPath:
          path: /sys/class/bluetooth
      - name: dev
        hostPath:
          path: /dev