apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: ble-collector
  namespaceSelector:
    matchNames:
      - default
  podMetricsEndpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
      scheme: http