replicaCount: 1
image:
  repository: ghcr.io/yum-ae/ble-collector
  pullPolicy: Always
  tag: "latest-arm64"

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

exporter:
  targetMacAddresses: "D4:35:34:35:68:4D,F2:B2:02:06:7C:49"
  hostNetwork: true
  privileged: true

# Prometheus Operatorを利用している場合
serviceMonitor:
  enabled: true
  interval: 60s
  labels: {} # PrometheusがServiceMonitorを認識するためのラベル