apiVersion: v1
kind: Service
metadata:
  name: {{ include "ble-exporter.fullname" . }}
  labels:
    {{- include "ble-exporter.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "ble-exporter.selectorLabels" . | nindent 4 }}
  ports:
    - name: http-metrics
      port: 8000
      targetPort: 8000
      protocol: TCP